name: studio_mac
description: iOS Assist Studio V2.0 Flutter Desktop Mac App.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  studio_design_system:
    path: ../../packages/studio_design_system
  studio_runtime:
    path: ../../packages/studio_runtime
  workflow_dsl:
    path: ../../packages/workflow_dsl

dev_dependencies:
  appium_client:
    path: ../../packages/appium_client
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
